### ISSUE TITLE
Please merge this commit

### ISSUE THREAD

**Issue by Mr-Bubble** [khusika/canting_kernel_xiaomi_msm8953#2]
https://github.com/0ctobot/neutrino_kernel_oneplus_sdm845/commit/6ad2d5020ef589ab591125c52c2352c6952ed6fa

**Comment by khusika** [comment]
Those mentioned configs has been included since 4.2.

**Comment by Mr-Bubble** [comment]
![Screenshot_20191004-005751_JuiceSSH](https://user-images.githubusercontent.com/15337062/66534851-25745900-eb4a-11e9-95d0-b0fc577b1a92.png)


But it no work on LA.UM.8.6.2.r1-04500-89xx.0

**Comment by khusika** [comment]
> ![Screenshot_20191004-005751_JuiceSSH](https://user-images.githubusercontent.com/15337062/66534851-25745900-eb4a-11e9-95d0-b0fc577b1a92.png)
> 
> But it no work on LA.UM.8.6.2.r1-04500-89xx.0

Ah yes, i missed this config `NETFILTER_XT_MATCH_OWNER`, will be enabled with the next release.

**Comment by Mr-Bubble** [comment]
I build kernel with enable NETFILTER_XT_MATCH_OWNER  ，now it work

**Comment by khusika** [comment]
I just keep this open till the next release, to avoid double discussion.

**Comment by Mr-Bubble** [comment]
But there is still a problem, I don't know how to solve it, the mobile network does not count, the network speed is always 0.
